"use client";

import Header from "@/app/(universal)/admin/components/Header";
import React from "react";
import "@/app/globals.css";
//import { Metadata } from "next";

import { SiteProvider } from "@/SiteContext/SiteProvider";
import SideBarBase from "./SideBarBase";
import { ButtonProvider } from "@/ButtonContext/ButtonProvider";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de" translate="no">
      <body>
        <SiteProvider>
        <ButtonProvider>
          <main className="relative flex text-slate-600">
            <SideBarBase />

            <div className="w-full flex flex-col ">
              <div className="lg:hidden">
                <Header />
              </div>
              <div className="w-full flex flex-col px-5 pt-17  bg-slate-100 h-screen ">
                {children}
              </div>
            </div>
          </main>
          </ButtonProvider>
        </SiteProvider>
      </body>
    </html>
  );
}
