import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "../globals.css";

import { CartProvider } from "@/store/CartProvider";
import { SiteProvider } from "@/SiteContext/SiteProvider";
import Header from "@/components/Custom/Header";

import { SideCart } from "@/components/MiniCart/SideCart";
import { BargerMenu } from "@/components/Bargermenu/Menu";
import Footer from "@/components/Custom/Footer";

import CartBottom from "@/components/CartBottom/CartBottom";
import Modal from "./components/Modal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    google: "notranslate",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body>
        <SiteProvider>
          <CartProvider>
            <BargerMenu />
            <Modal />
            <Toaster
              position="top-center"
              containerStyle={{
                top: "30%",
              }}
              toastOptions={{
                style: {
                  borderRadius: "10px",
                  padding: "12px 16px",
                  background: "#1e293b", // slate-800
                  color: "#f8fafc", // slate-50
                },
                success: {
                  style: {
                    background: "#10b981", // emerald-500
                    color: "#ffffff",
                  },
                },
                error: {
                  style: {
                    background: "#ef4444", // red-500
                    color: "#ffffff",
                  },
                },
                loading: {
                  style: {
                    background: "#f59e0b", // amber-500
                    color: "#ffffff",
                  },
                },
              }}
              reverseOrder={false}
            />
            <div className="z-50">
              <SideCart />
            </div>
            <Header />
            {children}

            <Footer />
            <div className="sticky  bottom-8 flex justify-end pr-4 z-50">
              <CartBottom />
            </div>
          </CartProvider>
        </SiteProvider>
      </body>
    </html>
  );
}
