import type { Metadata } from "next";
import "../globals.css";

import { CartProvider } from "@/store/CartProvider";
import { SiteProvider } from "@/SiteContext/SiteProvider";
import Header from "@/components/Custom/Header";

import { SideCart } from "@/components/MiniCart/SideCart";
import { BargerMenu } from "@/components/Bargermenu/Menu";
import Footer from "@/components/Custom/Footer";

import CartBottom from "@/components/CartBottom/CartBottom"
import Modal from "./components/Modal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body>
        <SiteProvider>
          <CartProvider>
            <BargerMenu />
            <Modal />
           <div className="z-50">
            <SideCart />
            </div>
            <Header />
            {children}
           
            <Footer />
            <div className="sticky  bottom-8 flex justify-end pr-4 z-50"><CartBottom /></div> 
          </CartProvider>
        </SiteProvider>
      </body>
    </html>
  );
}
