"use client";

import Header from "@/app/admin/components/Header";
import React from "react";
import "../globals.css";
//import { Metadata } from "next";

import { SiteProvider } from "@/SiteContext/SiteProvider";
import SideBarBase from "./SideBarBase";
import { ButtonProvider } from "@/ButtonContext/ButtonProvider";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <body>
        <SiteProvider>
        <ButtonProvider>
          <main className="relative flex border-0">
            <SideBarBase />

            <div className="w-full flex flex-col border-0">
              <div className="">
                <Header />
              </div>
              <div className="w-full flex flex-col p-5 mt-12 bg-slate-100 h-screen border-0">
                {children}
              </div>
            </div>
          </main>
          </ButtonProvider>
        </SiteProvider>
      </body>
    </html>
  );
}
